name: sim2seg
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - dm-control==1.0.5
    - dm-env==1.5
    - einops==0.4.1
    - glfw==2.5.4
    - gym==0.20.0
    - gym-notices==0.0.8
    - gym-unity==0.28.0
    - h5py==3.7.0
    - hydra-core==1.2.0
    - hydra-submitit-launcher==1.2.0
    - imageio-ffmpeg==0.4.7
    - importlib-metadata==4.12.0
    - labmaze==1.0.5
    - markdown==3.4.1
    - mlagents==0.28.0
    - mlagents-envs==0.28.0
    - mujoco==2.2.1
    - numpy==1.21.2
    - oauthlib==3.2.0
    - omegaconf==2.2.3
    - opencv-python==4.5.3.56
    - pathtools==0.1.2
    - pyopengl==3.1.6
    - submitit==1.4.5
    - tensorboard==2.8.0
    - termcolor==1.1.0
    - torch==1.11.0
    - torchaudio==0.8.0
    - torchvision==0.9.0
    - tqdm==4.64.0
    - wandb==0.13.1
